"""
DEMO: Inject simulated metadata into the bot to test the full pipeline.
This modifies the message processing to add realistic metadata for testing.
"""

import yaml
import time

print()
print("="*70)
print("METADATA TESTING - SETUP GUIDE")
print("="*70)
print()
print("The auto_reply_priv.py bot is READY to handle metadata!")
print()
print("📊 What happens when metadata arrives:")
print()
print("1️⃣  EXTRACTION (lines 2044-2061)")
print("   - Bot extracts rssi, snr, hop_count, hop_start from MeshCore")
print("   - Stores in metadata dict")
print()
print("2️⃣  AI CONTEXT (lines 1282-1286)")
print("   - Injects system message:")
print("     '[Metadata - Do not treat this as user message]'")
print("     'Signal strength: -65 dBm (good); SNR: 10 dB; Route: 2/5 hops'")
print()
print("3️⃣  HTML DISPLAY (lines 746-784)")
print("   - Creates colored badges:")
print("     🟢 -45 dBm = EXCELLENT")
print("     🟡 -65 dBm = GOOD")
print("     🟠 -78 dBm = MODERATE")
print("     🔴 -92 dBm = WEAK")
print()
print("4️⃣  MESSAGE LOG (line 2115)")
print("   - Stores metadata with each message for history")
print()
print("="*70)
print()

# Read current config
with open('lara_config.yaml', 'r', encoding='utf-8') as f:
    config = yaml.safe_load(f)

# Check if debug is enabled
debug_enabled = config.get('bot_behavior', {}).get('debug_auto_reply', False)

print("📝 CURRENT CONFIGURATION:")
print(f"   Debug mode: {'✅ ENABLED' if debug_enabled else '❌ DISABLED'}")
print(f"   Library polling: {config.get('bot_behavior', {}).get('use_library_polling', False)}")
print(f"   COM port: {config.get('radio', {}).get('port', 'NOT SET')}")
print()

if not debug_enabled:
    print("⚠️  Debug mode is OFF. To see detailed metadata logs:")
    print("   1. Edit lara_config.yaml")
    print("   2. Set bot_behavior.debug_auto_reply: true")
    print("   3. Restart the bot")
    print()

print("="*70)
print("🧪 TESTING METHODS")
print("="*70)
print()
print("Method 1: WAIT FOR REAL METADATA (when available)")
print("-" * 70)
print("  1. Run the bot: python auto_reply_priv.py")
print("  2. Send a message from another MeshCore node")
print("  3. Check lara_bot.log for metadata extraction:")
print("     '      Metadata: {rssi: -65, snr: 10, ...}'")
print("  4. Open http://127.0.0.1:8766/status to see badges")
print()

print("Method 2: TEMPORARY SIMULATION (for testing now)")
print("-" * 70)
print("  Add this to auto_reply_priv.py around line 2110:")
print()
print("  # TEMP: Simulate metadata for testing")
print("  import random")
print("  metadata = {")
print("      'rssi': random.randint(-95, -40),")
print("      'snr': random.randint(0, 15),")
print("      'hop_count': random.randint(0, 5),")
print("      'hop_start': 5")
print("  }")
print("  logger.info(f'🧪 SIMULATED METADATA: {metadata}')")
print()
print("  Then restart bot and send test messages.")
print()

print("Method 3: CHECK LIBRARY VERSION")
print("-" * 70)
print("  The MeshCore library may need updates to expose metadata:")
print()
print("  pip show meshcore")
print("  pip install --upgrade meshcore")
print()
print("  Check release notes for RSSI/SNR support.")
print()

print("="*70)
print("📋 VERIFICATION CHECKLIST")
print("="*70)
print()
print("✅ Code extracts rssi, snr, hop_count from messages")
print("✅ Code builds metadata dict and stores it")
print("✅ Code injects metadata into AI context")
print("✅ Code displays colored badges in HTML")
print("✅ Debug logging ready to show metadata")
print()
print("⏳ Waiting for:")
print("   [ ] MeshCore library to provide fields in get_msg()")
print("   [ ] Hardware/firmware to capture signal data")
print("   [ ] Real messages with metadata to test")
print()

print("="*70)
print("🎯 NEXT STEPS")
print("="*70)
print()
print("1. Run test: python test_metadata.py")
print("   → Verifies metadata extraction logic")
print()
print("2. Check API: python check_meshcore_api.py")
print("   → Shows what MeshCore library provides")
print()
print("3. Run bot: python auto_reply_priv.py")
print("   → Start bot and watch lara_bot.log")
print()
print("4. Send message from another node")
print("   → Check if metadata appears in logs")
print()
print("5. View dashboard: http://127.0.0.1:8766/status")
print("   → See colored signal strength badges")
print()

print("="*70)
print()
print("💡 TIP: The hardware is connected (COM6), so the bot is ready!")
print("    Just need the MeshCore library to provide the metadata fields.")
print()
